<?php

namespace Database\Seeders;

use App\Models\Make;
use Illuminate\Support\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class Product_MakeSeeder extends Seeder {
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run() {
        $makeList = ["ACCURA", "ACE", "ACTION CONSTRUCTION", "AJAX FIORI", "ALLWYN", "AMMANN APOLLO", "AMW", "API", "ASHOK LEYLAND", "ATITHI GOKUL", "ATUL AUTO", "Audi", "BAJAJ", "BEML", "BHARAT-BENZ", "BHARGAVI AUTO LTD", "BHURJEE MOTORS", "BULL MACHINES", "CAPTAIN", "CASE", "CATERPILLER", "CEL", "CHEVROLET", "CLASS", "CONSTRUCTION EQUIPMENT", "DCM TOYOTA", "DEUTZ FAHR", "DOOSAN", "DSR AUTO", "EICHER", "EICHER MOTORS", "EICHER POLARIS", "ESCORT", "E-YATRA", "FIAT", "FORCE", "FORCE MOTORS", "FORD", "GENERAL MOTORS", "GLM CO", "GODREJ", "GOEL TEMPO", "GOOD ENERGY INDIA", "GREAT AUTOMOTIVE PVT LTD", "GREAVES COTTON LTD", "HINDUSTAN MOTORS", "HINO", "HMT", "HONDA", "HYUNDAI", "INDO FARM", "ISUZU", "JCB", "JOHN DEERE", "JSA", "KAPIL AUTO", "KARTAR", "KAYEMEL MACHINES PVT LTD", "KERALA AUTOMOBILES LTD", "KOBELCO", "KRANTI AUTOMOBILE", "KRISHNA AUTO", "KS AGRO", "KUBOTA", "KUMAR MOTORS", "KURUKSHETRA AUTOMOBILES", "L&T", "LML MOTORS", "LOHIA", "LOTIAZ", "MAHINDRA", "MAHINDRA & MAHINDRA", "MAHINDRA AND MAHINDRA", "MAHINDRA GUJARAT TRACTOR", "MAHINDRA TRACTOR", "MAN-FORCE", "MANISH AUTO", "MARUTI", "MARUTI SUZUKI", "MASSEY FERGUSION", "MERCEDES", "MITSUBISHI", "MLR MOTORS (P) LTD", "MS AGRO", "MS AUTOMOBILES", "NANDI", "NEW HOLLAND", "NISSAN MOTORS", "OTHER", "PANCHNATH AUTO LTD", "PIAGGIO", "PREET", "PREMIER", "PRIYAA CRANES", "PUNJAB TRACTOR", "RAHUL AUTO LTD", "RASANDIK MOTORS", "RENAULT", "ROMAN AUTO", "SAERA ELECTRIC AUTO", "SAKSHAM", "SAME", "SAS MOTOR", "SCI LTD", "SCOOTERS INDIA LTD", "SHRI RAM DIESEL PVT LTD", "SMLISUZU", "SONA", "SONALIKA", "STANDARD", "STAR AUTO", "SWARAJ MAZDA", "SWARAJ TRCTOR", "TAFE", "TATA", "TATA MOTORS", "TEJA AUTO", "TELCO LTD", "TELCON", "TEREX", "TIL LIMITED", "TITAGARH AGRI PVT LTD", "TOYOTA", "TVS", "UMBRELLA CORP", "VAIBHAV", "VIBGYOR", "VIDHYUT", "VIKRAM", "VINAYAK", "VIPUL AUTO", "VOLKSWAGEN", "VOLTAS", "VOLVO", "VST TILERS LTD", "WIRTGEN INDIA PVT LTD", "XXPLORE AUTOMOTIVE (P) LTD", "CONTINENTAL ENGINES PVT LTD", "KION INDIA PVT LTD ", "SHREE NARAYAN EQUIPMENTS", "LIUGONG", "INTERNATIONAL TRACTORS LIMITED", "BAJAJ RICKSHAW", "ARJUN INDUSTRIES", "ALPHA  SP 453", "GROMAX AGRI EQUIPMENT LTD", "YUTONG", "Schwing Setter India Pvt Ltd", "EARTH MASTER", "Shree Ashapura", "ECO FUEL SYSTEM (I) PVT LTD", "Shree Vijay Trolly Works", "ASIA MOTOR WORKERS", "SWASTIK TRAILERS", "BHAGIRATH EQUIP", "MAHINDRA NAVISTAR", "ARGO", "VE COMMERCE", "SOLIS", "GK RICKSHAW", "JEEP COMPASS LIMITED"];

        $makeList1 = ["ALFA ROMEO", "ASHOK LEYLAND", "ASTON MARTIN", "Audi", "BAJAJ", "BENTLEY", "BHARAT-BENZ", "BMW", "CHEVROLET", "CHONGQING YUAN", "CHRYSLER", "DAEWOO", "DATSUN", "EICHER", "EICHER MOTORS", "ESCORT", "FERRARI", "FIAT", "FORCE", "FORD", "HERO", "HINDUSTAN", "HINDUSTAN MOTORS", "HMT", "HONDA", "HUMMER", "HYUNDAI", "INFINITI", "ISUZU", "JAGUAR", "JCB", "JOHN DEERE", "L&T", "LAMBORGHNI", "LAND ROVER", "MAHINDRA", "MAHINDRA & MAHINDRA", "MAHINDRA AND MAHINDRA", "MAHINDRA RENAULT", "MAHINDRA REVA", "MARUTI", "MARUTI SUZUKI", "MASERATI", "MERCEDES", "MERCEDES-BENZ", "MINI", "MITSUBISHI", "NEW HOLLAND", "NISSAN MOTORS", "OPEL", "PORSCHE", "PREMIER", "RENAULT", "ROLLS ROYCE", "SKODA", "SSANGYONG", "TAFE", "TATA", "TATA MOTORS", "TOYOTA", "VOLKSWAGEN", "VOLVO", "JEEP", "AGRO", "CONTINENTAL ENGINES PVT LTD", "KIA", "SKS", "SINGHAL ENTERPRISES", "ECOSMART", "MORRIS GARAGES", "KHALSA", "ATUT SANGAM ", "NOVA AUTOMOTIVE TECHNOLOGIES", "MISTUBISHI", "MG MOTOR", "MACONS EQUIPMENTS", "UNIPAVE", "SDLG", "TT", "SAHARA EVOLS", "SHREE NARAYAN EQUIPMENTS", "ACTION CONSTRUCTION EQUIPMENT", "ATHER EN", "INTERNATIONAL TRACTORS LIMITED", "POWERTRAC", "DAIMLER", "TAFE TRACTORS ", "CATERPILLAR (I) LTD", "BAJAJ RICKSHAW", "TESLA", "GREAVES INDIA PVT LTD ", "EIMCO ELECON", "V N IN-DUCTRIES", "Pradeep Argo Industries", "LEXUS", "Baoli", "BYD"];

        $makeList2 = ["ACCURA", "ACE MOTORS", "APRILIA", "ARIEL", "ATLAS", "AVON", "BAJAJ", "BENELLI", "BMW", "BSA", "CYNOSURE ENTERPRISES LTD", "DUCATI", "E BIKES", "EKO", "ENNES", "GLOBAL AUTO", "HARLEY DAVIDSON", "HERO", "HERO ELECTRIC", "HERO HONDA", "HERO MOTOCORP", "HONDA", "HUSQVARNA", "HYOSUNG", "HYUNDAI", "IDEAL JAWA LTD.", "INDIAN MOTORCYCLE", "INDUS ELECTRIC", "KANDA", "KAWASAKI", "KINETIC", "KOSMO", "KTM", "LECTRIX", "LML", "LOHIA", "MAHINDRA 2 WHEELERS", "MAJESTIC AUTO LTD", "MATCHLESS MOTORCYCLES", "MONTO MOTORS", "MORELLO YAMASAKI", "MOTO GUZZI", "MV AGUSTA", "OKINAWA", "OREVA ELECTRIC", "PARADISE ELECTRO AUTO", "PETRA", "PIAGGIO", "PRIMA POWER BIKE", "R K MOTORS", "REGAL", "ROTARY ELECTRONICS", "ROYAL ENFIELD", "SAERA ELECTRIC AUTO", "SINIC", "SUZUKI", "SYNERGY- ELECTRIC", "TRIUMPH", "TUNWAL", "TVS", "ULTRA MOTORS", "UM MOTORCYCLE", "VIBGYOR", "VIJAYA ", "WALKMAN WORLD", "XITE", "XS BIKES", "YAMAHA", "YASH", "YO BIKES", "YOUTH", "JAWA", "BATTRE ELECTRI MOBILITY BATTRE", "REVOLT", "TNR VEHICLES", "PURE ENERGY PVT LTD", "Ampere", "BLIX CYCLES AND E VEHICLES", "ODYSSE", "KOMAKI", "GALLOPS ELECTRIC", "ARYAION ELECTRIC VEHICLES", "OLA ELECTRIC", "Crayon Motors", "YEZDI", "ATHER", "JOY", "BGAUSS", "DISHMISH AUTOMOTIVE"];

        $values = [];
        $now = Carbon::now('utc')->toDateTimeString();
        foreach ($makeList as $value) {
            $values[] = ['product_id' => 1, 'name' => $value, 'created_at' => $now, 'updated_at' => $now];
        }
        foreach ($makeList1 as $value) {
            $values[] = ['product_id' => 2, 'name' => $value, 'created_at' => $now, 'updated_at' => $now];
        }
        foreach ($makeList2 as $value) {
            $values[] = ['product_id' => 3, 'name' => $value, 'created_at' => $now, 'updated_at' => $now];
        }
        Make::insert($values);
    }
}
